### ISSUE TITLE
[UI Logic] Passive Feedback additional info

### ISSUE THREAD

**Issue by Jason-KChen** [JKChenFZ/Minerva#103]
## Why/What
- ~~More content will be made available to the passive feedback graph, please adjust the UI to get ready~~ It is now available, see comments below
- Specifically, the context (in text) of the video at a timestamp (e.g. a x value in the graph) will be made available through an API.

## Guideline
1. We need to make the passive graph respond to clicks
2. fire a modal (e.g. sweetalert2) when an "x" value (any valid point on the line graph) on the passive feedback graph is clicked. The modal for now should say Analyzed context at <timestamp>

**Comment by Jason-KChen** [comment]
## Update:
- Backend is available, see following image for request format
![image](https://user-images.githubusercontent.com/12778917/99913947-7997b980-2cc8-11eb-839c-76896f10e869.png)

__note__: `duration` is the total time of the video

- Response
![image](https://user-images.githubusercontent.com/12778917/99913970-9af8a580-2cc8-11eb-81c2-8f4af9fc76ed.png)

Please render keys from both `bert` algorithm and `rake` algorithm on the UI

Pinging stakeholder @MrNickWan for exposure

**Comment by Jason-KChen** [comment]
Forgot about the dependency. Due to keyword extraction part being implemented in Python. Please install the corresponding python libraries.

1. Locate `py_scripts` under `backend`
2. Create a virtual environment with `python3` named `env` (must be named this way to work) under the directory above
3. Depdening on your machine, a `rust` compiler might be needed
4. Activate the virtual environment and install the dependencies specified in `requirements.txt`
5. You do not need to run `node index.js` with the virtual environment on. Nodejs will try to locate the virtual environment inside `env`
6. Good to go.

Pining stakeholder @MrNickWan  for exposure

**Comment by r00t-admin** [comment]
> Forgot about the dependency. Due to keyword extraction part being implemented in Python. Please install the corresponding python libraries.
> 
> 1. Locate `py_scripts` under `backend`
> 2. Create a virtual environment with `python3` named `env` (must be named this way to work) under the directory above
> 3. Depdening on your machine, a `rust` compiler might be needed
> 4. Activate the virtual environment and install the dependencies specified in `requirements.txt`
> 5. You do not need to run `node index.js` with the virtual environment on. Nodejs will try to locate the virtual environment inside `env`
> 6. Good to go.
> 
> Pining stakeholder @MrNickWan for exposure

I don't need node index.js?
I just activate the env but I don't pull any data.

**Comment by Jason-KChen** [comment]
@MrNickWan 
The existing procedure stays the same (e.g. how you run the server). You don't need to have the virtual environment activated as a pre-req before running `node index.js`

The server will try to locate the virtual environment on its own when the request comes in
