### ISSUE TITLE
[Big Bet] Repurpose Blazeface as Attention Tracker

### ISSUE THREAD

**Issue by Jason-KChen** [JKChenFZ/Minerva#105]
## Why/What
- Due to the nature of the real-time project roadmap/progress, the deliverable will most likely end up being too easy (in terms of difficulty) and low quality (missing various Nice2Have tagged issues, and many existing features are being implemented in the minimal way).
- Attention tracker seems to be a good fit with the existing Minerva ecosystem.
- With existing integration with Blazeface.js, a best-effort tracker can be implemented easily (e.g. by detecting existence of face/eyes).

## Guideline
1. More to come in the next few days.

Stakeholders: @JKChenFZ @MrNickWan 
cc @Yuliy97 for review in possible conflict in claiming impacts

**Comment by Yuliy97** [comment]
I feel like this overlapped with the big data quite a bit tbh.

**Comment by Jason-KChen** [comment]
> I feel like this overlapped with the big data quite a bit tbh.

I am assuming `blazeface.js` is still being used for face detection instead of the alternative `nodeface`. In such case, I am gonna reserve `facemesh.js` model to avoid collision. Different models should be safe from conflict, wdyt? @Yuliy97

**Comment by Yuliy97** [comment]
hmm, what exactly is the attention tracker suppose to be? Like track how long was the student's full face shown on the camera when watching the videos? I'm trying to see if there's other ways to do this

**Comment by Jason-KChen** [comment]
> Like track how long was the student's full face shown on the camera when watching the videos

For the most part, yes. Eye-sight tracking is avoided due to time constraint. `Webgazer.js` which provides eye-sight tracking comes with `facemesh` under the hood.

**Comment by Jason-KChen** [comment]
Dropped
