### ISSUE TITLE
Codebase Explanation

### ISSUE THREAD

**Issue by Jason-KChen** [JKChenFZ/Minerva#116]
## Why/What
- Codebase will be submitted twice as a whole but impact will only be claimed once
- Please locate the file named `Codebase Explanation` and complete the corresponding parts

**Comment by Jason-KChen** [comment]
File will be exported and submitted tomorrow (for real-time). @Yuliy97 @MrNickWan 

This file will be submitted again for BDS

**Comment by Yuliy97** [comment]
Should I add the BDS model related stuff after tomorrow then? So theres not as much overlap.

**Comment by Jason-KChen** [comment]
@Yuliy97, I don't think you need to specifically mention/list all the models at all in this file. This is just to certify all features are proposed and submitted independently. The other document does need all the models listed for BDS

**Comment by Jason-KChen** [comment]
@Yuliy97 @MrNickWan last person to work on this doc gets to write the first paragraph

**Comment by Yuliy97** [comment]
Isn't this just for real time? Where's the Codebase Explanation file?

**Comment by Jason-KChen** [comment]
@Yuliy97 I thought we are on the same page (in terms of understanding) yesterday? Looks like no longer the case? The file is in the same location as specified in the issue description. It is __not__ just for real-time because there is a chain of dependency (BDS works depends on RTS work under the hood)

**Comment by Jason-KChen** [comment]
@Yuliy97  How is it only for real-time........ The same codebase is submitted twice as stated in the description. You can not claim credits on things twice ............................................................

**Comment by Yuliy97** [comment]
Nvm I found the file. Is on the Google drive. The issue does not mention where the file is located and made it very confusing since I'm not in both classes.

**Comment by Yuliy97** [comment]
> @Yuliy97 @MrNickWan last person to work on this doc gets to write the first paragraph

First paragraph cover the reason why the code based should be use for both classes. I'm not in both in both section, so I don't think I'm the best person to write it.

**Comment by Jason-KChen** [comment]
renamed the file to `README`
