### ISSUE TITLE
Video Stat Analytical Dashboard UI Foundation/Mock

### ISSUE THREAD

**Issue by Jason-KChen** [JKChenFZ/Minerva#30]
As part of the Minerva teacher analytical dashboard, we want to a have full webpage for analytical purposes. 

To get started, let's have a foundation UI structure rolling.
1. Let's try to setup the web page similar to the approach in #29 . We don't want to visit another remote website to access the analytical dashboard. Instead, we want a secret button (accessed via chrome extension management or the popup UI) which opens a new tab with HTML supplied from the extension.
2. For this issue, make your own fake data
3. The analytical dashboard design is up to you in the first iteration by subject to the following constraints
4. A list of Youtube video with title (let's say they are in a list where each row is a youtube video title)
5. For each youtube video title, every row is expandable (like accordion)
6. In the expanded panel, we should have a time series chart/graph with two types of markers where one type is for active feedback and the other is for passive feedback. Each marker should have a count (how many times this signal was received/detected). Again, design up to you, but the deliverable should be clear and fulfill the constraints above

Good practices to keep in mind:
1. Keep your pull request/commits small, anything over 100+ lines in a pull request incurs unnecessary overheads on the reviewer
2. While working on the same issue, it is okay to have multiple branches. E.g. If you have 4 different sub-tasks, have each sub-task in its own branch. The second task should be based(branches off) on the first task. As with pull requests, open and close then sequentially.
3. In the commit message, prefix the message with `[#issueNumber]` like `[#1]` for easy referencing. You don't have to do that for small commits like fixing a line
4. Once a pull request is opened, check the linter and the code you submitted (under `changed files` tab) to make sure everything is correct
5. After revision, please re-request review by clicking on the circle next to reviewer names
6. If the change has to do with UI, please include screenshots of the changed UI as part of the pull request
7. If your feature branch is stale, always `rebase` instead of `merge`. Also try to avoid `force pushes`

**Comment by r00t-admin** [comment]
What do you mean by HTML supplied by extension?
Do you want to manually inject the HTML and javascript into an empty page?
Or do you want something else?

Currently, I am going to just create an HTML page with a corresponding javascript file.

**Comment by Jason-KChen** [comment]
As long as the source code comes from the extension.
