### ISSUE TITLE
Inject some organic course content for testing and workshop/demo

### ISSUE THREAD

**Issue by Jason-KChen** [JKChenFZ/Minerva#60]
Current content on the course `Test 123` contains NSFW material. As part of demo/workshop recording, we will need organic content posted on the google classroom

Organic content: something (e.g. announcement/assignment) you would see in a true and legit remote classroom

For this issue, please do the following,
1. Create a brand new google classroom
2. Import/Generate/Create/Migrate at least five organic content inside the `stream` tab or `classwork` tab
     - At least two organic content must contain a youtube link each.
3. Post the link here once you are done

**Comment by r00t-admin** [comment]
This should be resolved.

Yuli has created a new classroom and new assignments have been added.
