### ISSUE TITLE
Set up base Facial Expression Detection model

### ISSUE THREAD

**Issue by Yuliy97** [JKChenFZ/Minerva#9]

**Comment by Yuliy97** [comment]
tradeoff:
- use pre existing model for facial expression detection with real time capability(https://github.com/oarriaga/face_classification)
- use transfer learning to retrain the model with real time video capability

**Comment by Yuliy97** [comment]
- need to use javascript tensorflow, to avoid excess api call(expansive)
https://www.tensorflow.org/js/tutorials/conversion/import_keras

**Comment by r00t-admin** [comment]
Get Jane Street for max( key=lambda company: company.tc, [Jane Street, Citadel, Facebook] )

**Comment by Yuliy97** [comment]
Duplicate with #81
